server2/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name = 'results'),
    path('results', views.results, name = 'results'),
]

server2/server2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('', admin.site.urls),
]

server2/app/models.py
from django.db import models

# Create your models here.

server2/app/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
import requests

def index(request):
	return render(request, 'app/index.html', {})

def results(request):
	if request.method == "POST":
		response = requests.post("http://127.0.0.1:8000/polls/1/vote/", {"choice":request.POST['choice']})
	return HttpResponse(requests.get("http://127.0.0.1:8000/polls/1/results/"))

server2/app/templates/app/index.html
<h1>Question 1 of other server</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app:results'%}" method="post">
<!-- {% csrf_token %} -->
<input type="radio" name="choice" id="1" value="1">
<label for="choice1">Choose choice 1</label><br>
<input type="radio" name="choice" id="2" value="2">
<label for="choice2">Choose choice 2</label><br>
<input type="radio" name="choice" id="3" value="3">
<label for="choice3">Choose choice 3</label><br>
<input type="submit" value="Vote">
</form>

server2/app/templates/app/random.html
<p> hi </p>